# Generated by Django 3.1.7 on 2021-03-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ground', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('manager', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('avarta', models.ImageField(upload_to='')),
                ('founded', models.DateField()),
                ('league', models.CharField(max_length=100)),
                ('link_detail', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'FootballClub',
            },
        ),
        migrations.CreateModel(
            name='Footballer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('birthday', models.DateTimeField()),
                ('height', models.IntegerField()),
                ('position', models.CharField(choices=[('GOALKEEPER', 'GOALKEEPER'), ('DEFENDER', 'DEFENDER'), ('MIDFIELDER', 'MIDFIELDER'), ('ATTACKER', 'ATTACKER')], default='FOOTBALLER', max_length=10)),
                ('current_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FootballClub')),
            ],
            options={
                'db_table': 'Footballer',
            },
        ),
    ]
